language: generic
dist: trusty
sudo: required

group: deprecated-2017Q2

before_install:
  - echo "machine github.com login $GH_TOKEN" >> ~/.netrc
  - env -0 | while IFS='=' read -r -d '' n v; do echo "$n"="$(echo $v)";done | grep  'TRAVIS\|CI\|SAUCE\|GIT\|REPO\|BRANCH' >> script/docker/env
  - shopt -s expand_aliases
  - source script/docker/activate
  - npm --version

install:
  - npm install --quiet

script:
  - npm run-script travis_script

after_success:
  - npm run-script travis_after_success
