name: Continous integration

on:
  pull_request:

jobs:
  integration-check:
    runs-on: ubuntu-latest

    environment: github-ci

    strategy:
      matrix:
        node-version: [6.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install -g bower@1.8.12 grunt-cli@1.3.2
          npm install

      - name: Build GCWeb-OPC
        run: grunt dist test-mocha
