name: Continous integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  integration-check:
    runs-on: ubuntu-latest

    environment: github-ci

    strategy:
      matrix:
        node-version: [6.x]
        java-version: [8]
    steps:
      - uses: actions/checkout@v2

      - name: Use Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
          java-package: jre

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install -g bower@1.8.12 grunt-cli@1.3.2
          npm install
        env:          
          OPENSSL_CONF: /dev/null

      - name: Build GCWeb-OPC
        run: grunt dist
